### PR TITLE
Expose cv::Moments

### LINKED ISSUE #85: [ImgProc] Moments type are not exposed in bindings.
In bindings
```javascript
Moments moments_wrapper(const cv::Mat& arg1, bool arg2) {
    return cv::moments(arg1, arg2);
}
```
Moments type are not exposed in bindings.

### PR DESCRIPTION
**Pull request by huningxin**
Fix #85

### CODE REVIEW

**Comment by huningxin** [comment]
@ganwenyao , please take a look. Thanks!

**Comment by huningxin** [comment]
I am going to add a test for it.

**Comment by ganwenyao** [comment]
@huningxin It looks good!

**Comment by huningxin** [comment]
@ganwenyao , could you please help provide a test case? Thanks!

**Comment by huningxin** [comment]
Add unit tests from https://github.com/huningxin/opencv/issues/102 from @ganwenyao . Please take another look. Thanks!

**Comment by ganwenyao** [comment]
@huningxin  It works successfully.

**Pull request merged**
