### PR TITLE
Exclude cv::Mat for vecFromJSArray

### LINKED ISSUE #82: [ImgProc] different argument type between bindings and C++
In C++
```C++
void cv::drawContours(InputOutputArray image, InputArrayOfArrays contours, int contourIdx, const Scalar & color, int thickness = 1, int lineType = LINE_8, InputArray hierarchy = noArray(), int maxLevel = INT_MAX, Point offset = Point())		
```
In bindings
```javascript
void drawContours_wrapper(cv::Mat& arg1, const emscripten::val& arg2, int arg3, const Scalar& arg4, int arg5, int arg6, const cv::Mat& arg7, int arg8, Point arg9) {
        return cv::drawContours(arg1, emscripten::vecFromJSArray<cv::Mat>(arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }
```
* In C++, the arg2(InputArrayOfArrays contours) is vector<vector<Point>> type, but in bindings, arg2 is cv.MatVector type.
* In C++, the arg7(InputArray hierarchy) is vector\<Vec4i\> type, but in bindings, arg7 is cv.Mat type.
* noArray() is not supported in bindings.

### PR DESCRIPTION
**Pull request by huningxin**
Fix #82

### CODE REVIEW

**Comment by huningxin** [comment]
@ganwenyao , please help test. Thanks!

**Comment by ganwenyao** [comment]
@huningxin  It has a BindingError.

**Comment by huningxin** [comment]
> @huningxin It has a BindingError.

@ganwenyao , could you please provide the test code?

**Comment by ganwenyao** [comment]
@huningxin  It works successfully.

**Comment by huningxin** [comment]
Thanks for validation! Merging.

**Pull request merged**
