### PR TITLE
Js platform

### LINKED ISSUE #204: Add OpenCV.js build script into platforms/js
Vadim's suggestions:

1.	Instead of patching main CMake scripts heavily, it would be better to add a subdirectory to opencv/platforms, e.g. opencv/platforms/js or opencv/platforms/web, where you can put python script to build OpenCV.js, and there you can call cmake with proper flags, e.g. explicitly disable GTK, OPENNI2 etc.
2.	Correspondingly, the installation tutorial https://huningxin.github.io/opencv_docs/tutorial_js_setup.html can be simplified - some of the logic or most of the logic can be put to the build script.

### PR DESCRIPTION
**Pull request by huningxin**
Fix #204

### CODE REVIEW

**Comment by huningxin** [comment]
@ganwenyao , please take a look. Thanks!

**Comment by ganwenyao** [comment]
@huningxin In my building, there is an error:
screenshot from 2017-09-08 16-05-22

**Comment by huningxin** [comment]
The script will find the emscripten by either EMSCRIPTEN environment variable or --emscripten_dir option. In your case, you didn't provide the --emscripten_dir option, so please make sure the EMSCRIPTEN envrionment variable has the right value.

**Comment by ganwenyao** [comment]
@huningxin 
loadImageToCanvas("LinuxLogo.jpg", "absSobelCanvasInput"); should be changed to 
loadImageToCanvas("shape.jpg", "absSobelCanvasInput");  in js_gradients.markdown

**Comment by huningxin** [comment]
Good catch! I am fixing it. Any other issues?

**Comment by huningxin** [comment]
@ganwenyao , pushed a commit to fix that issue. Please take a look.

**Comment by ganwenyao** [comment]
Some loading problem in js_trackbar.markdown.  Others look good!

**Comment by huningxin** [comment]
Thanks @ganwenyao ! I've uploaded a new commit to fix it.

**Pull request merged**
