### PR TITLE
[Opencv.js doc] Init commit to add semantic segmentation example

### LINKED ISSUE #316: [DNN] add segmentation js example

### PR DESCRIPTION
**Pull request by akineeic**
Fix #316

### CODE REVIEW

**Comment by akineeic** [comment]
I have tested the models for semantic segmentation in the [wiki](https://github.com/opencv/opencv/wiki/Deep-Learning-in-OpenCV). The [ResNet101_DUC_HDC](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/duc) can't be read correctly. The output image of [Enet](https://github.com/e-lab/ENet-training) doesn't look good visually, and the inference time of [FCN](https://github.com/shelhamer/fcn.berkeleyvision.org) is too long (need about six minutes). So I just use the deeplabV3 model you mentioned [here](https://github.com/opencv/opencv/issues/17362#issuecomment-634407860) for the js example. The results are shown below.

- Enet

Enet


- FCN

FCN



- DeeplabV3

DeeplabV3

**Comment by huningxin** [comment]
So let's use the deeplab v3 as the default model. BTW, did you see similar results in native python example? Please update that in #315 . And please report corresponding issues to upstream opencv for more guidelines.

**Comment by akineeic** [comment]
Thanks for your reminder. I update the results and put the upstream issue into #315.

**Comment by huningxin** [comment]
That's good. Let's merge this PR.

**Pull request merged**
