### PR TITLE
Layer test

### LINKED ISSUE #329: [GPU] implement operations
- [x] OpConcat
- [x] OpConv
- [x] OpLrn
- [x] OpPermute
- [x] OpPool
- [x] OpPriorBox
- [x] OpRelu
- [x] OpSoftmax

### PR DESCRIPTION
**Pull request by NALLEIN**
### Pull Request Readiness Checklist
Fix #329 
The test method is as follows
Set test data path
```
git clone https://github.com/opencv/opencv_extra.git
export OPENCV_TEST_DATA_PATH=${PATH_TO}/opencv_extra/testdata
```
Test ops 
```
git clone https://github.com/NALLEIN/opencv.git
cd opencv/
git checkout -b layerTest origin/layerTest
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release -DWITH_WEBGPU=ON -D CMAKE_INSTALL_PREFIX=/usr/local ..
make -j8
$(PATH_TO_OPENCV)/build/bin/opencv_test_dnn --gtest_filter=*layers*
```
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by huningxin** [comment]
@NALLEIN , after PR #338 merged, please clean this PR and rebase to gsoc_2020_gpu branch.

@wzw-intel , please help review the ops implementation.

**Comment by NALLEIN** [comment]
Run all test case about layers:
```$(PATH_TO_OPENCV)/build/bin/opencv_test_dnn --gtest_filter=*layers*```
There is one test case about layer that failed:
```
[ RUN      ] Test_Caffe_layers.Concat/1, where GetParam() = WEBGPU/DAWN
/home/webml/GSoC/Forked/opencv/modules/dnn/test/test_common.impl.hpp:72: Failure
Expected: (normL1) <= (l1), actual: 0.207264 vs 1e-05
/home/webml/GSoC/Forked/opencv/modules/dnn/test/test_common.impl.hpp:75: Failure
Expected: (normInf) <= (lInf), actual: 3.72753 vs 0.0001
[  FAILED  ] Test_Caffe_layers.Concat/1, where GetParam() = WEBGPU/DAWN (81 ms)
```
and this problem can be reproduced by runing[ this test case](https://github.com/huningxin/opencv/pull/354/files#diff-e4e00299c1316b7b1e5086f33b0e51f5R1669)
```$(PATH_TO_OPENCV)/build/bin/opencv_test_dnn --gtest_filter=*testCaffeLayers.Accuracy*```
The specific reason is  that the conv48.comp shader occurs an error when computing convolution, I may need some help to locate and solve the problem. Please help to review the corresponding code if you have time.
@huningxin @wzw-intel  PTAL.

**Comment by NALLEIN** [comment]
Now the WGPU backend could pass all the test case about layers using following instructions:
Set test data path
```
git clone https://github.com/opencv/opencv_extra.git
export OPENCV_TEST_DATA_PATH=${PATH_TO}/opencv_extra/testdata
```
Test ops 
```
git clone https://github.com/NALLEIN/opencv.git
cd opencv/
git checkout -b layerTest origin/layerTest
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release -DWITH_WEBGPU=ON -D CMAKE_INSTALL_PREFIX=/usr/local ..
make -j8
$(PATH_TO_OPENCV)/build/bin/opencv_test_dnn --gtest_filter=*layers*
```
@huningxin @wzw-intel PTAL.

**Comment by NALLEIN** [comment]
Done in upstream [PR](https://github.com/opencv/opencv/pull/18066).

**Pull request closed without merging**
