### PR TITLE
Value object

### LINKED ISSUE #147: Bind cv.Scalar to JS array
Current usage of Scalar
```js
let s = new cv.Scalar(0, 1, 2, 3);
let mat = new cv.Mat(2, 2, cv.CV_8UC4, s);

for (let r = 0; r < mat.rows; r++) {
  for (let c = 0; c < mat.cols; c++) {
    let element = mat.ptr(r, c);
    assert.equal(element[0], 0);
    assert.equal(element[1], 1);
    assert.equal(element[2], 2);
    assert.equal(element[3], 3);
  }
}

mat.delete();
s.delete();
```
After binding to JS array
```js
let mat = new cv.Mat(2, 2, cv.CV_8UC4, [0, 1, 2, 3]);

for (let r = 0; r < mat.rows; r++) {
  for (let c = 0; c < mat.cols; c++) {
    let element = mat.ptr(r, c);
    assert.equal(element[0], 0);
    assert.equal(element[1], 1);
    assert.equal(element[2], 2);
    assert.equal(element[3], 3);
  }
}

mat.delete();
```

Pros:
* No need to new cv.Scalar
* No need to explicit delete() call

Cons:
* No constructor overloading, like new cv.Scalar(0)

### PR DESCRIPTION
**Pull request by huningxin**
Fix #147 and #154

### CODE REVIEW

**Comment by huningxin** [comment]
@pancx @ganwenyao , please take a look. Thanks!

**Comment by ganwenyao** [comment]
Looks good!

**Comment by pancx** [comment]
Excellent work!

**Comment by huningxin** [comment]
Thanks for review! I am going to merge it. You can update the tutorials once Mat change is in place.

**Pull request merged**
