### PR TITLE
Fix memory issue of matFromArray

### LINKED ISSUE #37: cv::Mat clone() gives wrong value
While using clone(), it gives wrong value sometimes. For example, in featrues_2d.html line 179, change img to img.clone(), there will be some wrong value in the row 1 of the output image, just like the attach file.

new bitmap image

### PR DESCRIPTION
**Pull request by huningxin**
Fix #37

### CODE REVIEW

**Comment by huningxin** [comment]
@pancx , please help verify the fix in your tests. @sajjadt , please review. Thanks!

**Comment by pancx** [comment]
Cool! I tried it. And in cv.imread
```
var src = cv.matFromArray(imgData, cv.CV_8UC4);
var dst = new cv.Mat();
dst = src.clone();
src.delete();
return dst;
```
could return src directly now.

**Comment by huningxin** [comment]
@pancx , thanks for validation!

**Comment by huningxin** [comment]
I am going to merge this fix. We can follow up if there are any issues.

**Pull request merged**
