### PR TITLE
Unit test for 64-bit, countnonZero, Mat.dot, split, merge

### PR DESCRIPTION
**Pull request by lionkunonly**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under OpenCV (BSD) License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by lionkunonly** [comment]
#340

**Review by huningxin — CHANGES_REQUESTED** [review]
Thanks for the PR! The tests in `test` folder is using QUnit for unit testing. For perf test, you should follow the tests inside `perf` folder where it uses benchmark.js as framework.

My suggestion:
1. make this PR as unit tests enhancement by adding each kernels into its category, e.g. img_proc etc.,
2. create another PR to add the perf tests

**Comment by lionkunonly** [comment]
Thanks for your suggestions. I will complete the suggestion 2 firstly.

**Comment by huningxin** [comment]
> Thanks for your suggestions. I will complete the suggestion 2 firstly.

Sounds good. Once you change this PR, feel free to ping me for review.

**Pull request closed without merging**
