### PR TITLE
Update tutorials to apply new code style about base data type and mat change

### LINKED ISSUE #166: Change pictures in tutorials
Try to use general images within opencv repo. 
- Use images from opencv repo
- Use general images, avoid trademark etc.,

### PR DESCRIPTION
**Pull request by pancx**
Update tutorials to apply new code style cause #172 
Fix #166 , replace windowsLogo.jpg and linuxLogo.jpg with apple.jpg and orange.jpg(from opencv/samples/data)

### CODE REVIEW

**Comment by pancx** [comment]
@huningxin Please have a look.

**Comment by pancx** [comment]
@huningxin wait, I will check again whether mats are deleted

**Comment by pancx** [comment]
@huningxin Add a new commit, please have a look.

**Comment by huningxin** [comment]
Looks good. Merging.

**Pull request merged**
