### PR TITLE
Fix opencv.js load failure in d8

### PR DESCRIPTION
**Pull request by huningxin**

### CODE REVIEW

**Comment by huningxin** [comment]
@Wenzhao-Xiang , PTAL.

**Comment by Wenzhao-Xiang** [comment]
@huningxin Web worker need to treat `cv` as a function name, so this PR will cause loading issue in threads. We may need to detect web worker or d8 environment to seperate them from each other.

**Comment by Wenzhao-Xiang** [comment]
For web worker environment detect, mmscripten does:
```js
var ENVIRONMENT_IS_WORKER = typeof importScripts === 'function';
```
https://github.com/emscripten-core/emscripten/blob/7f9e788e14998031ad4bccb997d51258a8e23c04/src/shell.js#L68

**Comment by huningxin** [comment]
Good catch and suggestion, thanks @Wenzhao-Xiang . I will fix that and update the PR.

**Comment by huningxin** [comment]
Fixed as your suggestion. Please take another look. @Wenzhao-Xiang

**Comment by huningxin** [comment]
I verified it works with multi-threads (worker) build.

**Comment by Wenzhao-Xiang** [comment]
It also works on my machine.
LGTM! Thanks!

**Review by Wenzhao-Xiang — APPROVED** [review]

**Comment by huningxin** [comment]
good review. merged.

**Pull request merged**
