### PR TITLE
Simd fallback

### PR DESCRIPTION
**Pull request by huningxin**
Integrate @Wenzhao-Xiang 's wasm simd impl and fallback impl

### CODE REVIEW

**Comment by huningxin** [comment]
@Wenzhao-Xiang , PTAL.

There are two commits:
https://github.com/huningxin/opencv/pull/282/commits/29097c7eaf1ef9d94754f8de459685a531d3a1e6 just drop your impl into the intrin_wasm.hpp

https://github.com/huningxin/opencv/pull/282/commits/dc5fd82fc693167a291982e5200940813f7116f5 rewrite your c++ impl by reusing fallback impl.

**Comment by Wenzhao-Xiang** [comment]
@huningxin Please drop the latest code in my branch: https://github.com/Wenzhao-Xiang/opencv/tree/opencvjs_simd

**Comment by huningxin** [comment]
OK, is the version https://github.com/Wenzhao-Xiang/opencv/commit/cca4f6cea6d50293e754b77a8a228c7db876c856 OK? Please make sure it is the  latest version of your work.

**Comment by Wenzhao-Xiang** [comment]
The latest may be https://github.com/Wenzhao-Xiang/opencv/commit/7e5f4e0618a45a85830cd517dfc60ae4ea57e96f. Or I can send a PR first to check in my code and you can rebase on it to add fallback section? I think this can make sure all things works. WDYT? @huningxin

**Comment by huningxin** [comment]
Thanks. It requires some changes in the fallback impl as well. Let me handle that. I will use Wenzhao-Xiang@7e5f4e0.

**Comment by huningxin** [comment]
@Wenzhao-Xiang , merged your latest code. Passed all the tests. Please take another look.

**Comment by huningxin** [comment]
I found the latest version would crash my chrome (76.0.3809.100) for cvtcolor perf test. Did you meet the same issue?

**Comment by Wenzhao-Xiang** [comment]
> Passed all the tests. Please take another look.

LGTM.
I met the same issue on my machine(same chrome version with yours)

**Comment by huningxin** [comment]
Let's merge it and focus on the resize perf tuning.

**Pull request merged**
