### PR TITLE
Optimize Perf tests

### LINKED ISSUE #305: [Perf] optimize the perf tests
1. reuse code as much as possible
2. allow to run multiple kernels in one page

### PR DESCRIPTION
**Pull request by lionkunonly**
for #305

### CODE REVIEW

**Comment by lionkunonly** [comment]
I have deleted the redundant code in the initial `CvtColor`, `Resize`,`Threshold` perf-test. The functions that play similar roles are moved to the file  `perf_helpfunc.js`. However, two functions `decodeParams2Case` and `genBenchmarkCase` are retained because I think they are used to parse the input parameters and construct their own perf test cases, though they play similar roles.  If you have any suggestions to optimize the two functions, please let me know.

**Comment by lionkunonly** [comment]
The workflow for the perf test for a kernel in my design:
1、Consturct the default combination for the kernel. 
2、Design the function like `addCvtColorCase` and `addCvtModeCase` to set the `Benchmark.Suite` for the kernel.
3、Create function `decodeParams2Case` and `genBenchmarkCase` to parse the input and set test case.
4、Use function `setBenchmarkSuite` to print the log in console.

**Comment by huningxin** [comment]
@lionkunonly , according to the review meeting, please move the common functions of `decodeParams2Case` into `perf_helpfunc.js`. Then we are fine to merge this PR.

**Comment by lionkunonly** [comment]
@huningxin @terfendail  I have moved the common functions of `decodeParams2Case` into `perf_helpfunc.js`.  Please review it, if it is ok, this PR can be merged.

**Review by huningxin — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
