### PR TITLE
Expose intrin tests

### PR DESCRIPTION
**Pull request by huningxin**
Steps:
1. Build with --build_wasm_intrin_test
2. Execute tests in console, e.g. cv.test_hal_intrin_float32()

### CODE REVIEW

**Comment by huningxin** [comment]
Fix https://github.com/huningxin/opencv/issues/257#issuecomment-520328897

@Wenzhao-Xiang @terfendail , PTAL.

**Comment by Wenzhao-Xiang** [comment]
@huningxin LGTM! 
The log message like 
`
TheTest<R> &cv::hal::TheTest<cv::hal_baseline::v_uint32x4>::test_interleave() [R = cv::hal_baseline::v_uint32x4] (~opencv/build_simd/modules/js/../../../modules/core/test/test_intrin_utils.hpp:366): FAIL
` can clearly tell me where something went wrong. That really support me greatly. 
Thanks for your great contribution!

**Comment by huningxin** [comment]
@Wenzhao-Xiang , I pushed another commit that enable gtest checks and assertions. It would provide more accurate checks and more detailed trace info. And it also add a function `test_hal_intrin_all` to run all the tests. Please have a try.

**Comment by huningxin** [comment]
Just synced with @Wenzhao-Xiang , this tool can help him to fix wasm intrin issues. Let's merge it and keep the wasm intrin development moving forward. @terfendail , if you have any suggestions, feel free to let us know. We can follow up in later PRs.

**Pull request merged**
