### PR TITLE
Improve examples error handling

### LINKED ISSUE #217: Improve the output of cv::Exception
According to review comments of opencv#9466

### PR DESCRIPTION
**Pull request by huningxin**
Handle:
1. opencv.js loading errors
2. script errors (Error)
3. cv::Exception

Fix #217

### CODE REVIEW

**Comment by huningxin** [comment]
@ganwenyao , Please take a look. Thanks!

**Comment by huningxin** [comment]
@ganwenyao , updated the PR to add parameter to `onOpenCvLoadError` function. Please take another look.

**Comment by ganwenyao** [comment]
@huningxin It looks good!

**Comment by huningxin** [comment]
Thanks!

**Pull request merged**
